# Page settings
baseurl = "www.oportoprint3d.eu"
title = "OportoPrint3d"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "OportoPrint3d"
    home = "Início"
    work = "Work"
    testimonials = "Testimonials"
    services = "Para quem?"
    about = "Equipa"
    contact = "Inscrição"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "É agora!<br>Constrói a tua Impressora 3D"
    subtitle = 'Durante as 20h do workshop,<br>vais construir a tua Impressora 3d, aprender modelação 3D e começar a imprimir para não mais parar!'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Montagem"
    description = "Montagem individual de Impressora 3D Anet A8 + updates + Raspberry c/ câmara, em kit ."
    url = "workshop/montagem"
    button = "Com o quê?"
    icon = "icon-wrench"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Modelação 3D"
    description = "Noções de modelação tridimensional (criação de modelos em Autodesk Inventor)."
    url = "workshop/modelacao-3d"
    button = "Que precisas?"
    icon = "icon-laptop"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Impressão"
    description = "Impressão tridimensional do objecto modelado."
    url = "workshop/impressao"
    button = "A acção?"
    icon = "icon-hand-o-up"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Para quem?"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Designers &amp; Engenheiros"
      description = "Garantidamente neste workshop vais aprender novas linguagens, ferramentas e conhecimento para executar os seus protótipos e projetos."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Empreendedores"
      description = "Compreender os potenciais da tecnologia inerente a impressão 3D e explorar a oportunidade de aplicar esta tecnologia a tua ideia de negócio."
      icon = "icon-layers2"
      
    [[params.services.item]]
      title = "Makers &amp; Entusiastas 3D"
      description = "Vem-te divertir partilhando a tua experiência e conhecimentos em open source e 3d printing! Precisamos de ti nesta equipa que acredita que o futuro é agora!"
      icon = "icon-video2"

      [[params.services.item]]
      title = "Estudantes (> 16 anos)"
      description = "Interessados em robótica, habituados a montar kits, com conhecimentos básico em 3D Printing. Aqui podes partilhar experiências com a comunidade Maker e libertar a tua criatividade e a imaginação."      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Equipa"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Gaspar Santos"
      position = "Apaixonado Open source"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Miguel Magalhães"
      position = "Arquiteto"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Marta Padilha"
      position = "Consultora Creativa"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Participantes"
      icon = "icon-people"
      from = 0
      to = 10
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Inscreve-te"
    description = "Hoje, digo eu, pois amanhã é passado!."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Rua da Paz 66, 5º piso, Sala 56<br> 4050-461 Porto, Portugal"],
        ["icon-phone", "(+351) 91-818-8668 / 91-462-2417"],
        ["icon-envelope", "info@oportoprint3d.eu"],
        ["icon-globe", '<a href="http://www.oportoprint3d.eu/" target="_blank">OportoPrint3d</a>']
      ]

    name = "Nome"
    email = "Email"
    phone = "Telemóvel"
    message = "Mensagem"
    button = "Enviar"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; OportoPrint3d. All Rights Reserved. <br>Created by <a href="http://gasparsantos.eu/" target="_blank">ME</a> with <a href="http://gohugo.io/" target="_blank">Hugo</a><br>Inspired in: <a href="https://github.com/saey55" target="_blank">Elato Theme</a>'
